### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by ewoudwerkman** [masagroup/soft.ts#20]
I was checking out this repository to check if I could use my ecore model in JS/TypeScript. I got it working, but run into some issues with the code (among others the EEnum class has issues with capitalization of the getters). 

I wanted to create a pull request, but this version of the repo does not contain all the files, compared to the package at npm (e.g. EEnum and EEnumImpl classes are missing).

Is it possible to push the latest version that is also used in the npm package?

**Comment by SokaDance** [comment]
solved with v1.1.0
