### ISSUE TITLE
Porting EMF to TypeScript

### ISSUE THREAD

**Issue by schwichti** [masagroup/soft.ts#8]
Hi,
 I just found this repository and wanted to let you know that I'm working on CrossEcore which you can use to [generate](https://github.com/crossecore/crossecore-generator) TypeScript/Javascript, C# and Swift code from Ecore (with OCL). This also includes [runtime library for TypeScript](https://github.com/crossecore/ecore-typescript), C# and Swift.

What license is Soft released under? Will the Soft.ts be further developed? An interesting approach is to compile C++ model code according to WebAssembly.

**Comment by SokaDance** [comment]
Hi,
Soft.TS is licensed under MPL V2. 
It will be further developped but for the moment i am focusing on the Go version : [Soft.Go](https://github.com/masagroup/soft.go). 
A C++ version is also available there : [Soft.Cpp](https://github.com/masagroup/soft.cpp). 
You can find all the corresponding generators here : [Soft.Gen](https://github.com/masagroup/soft.gen). They are written  with Eclipse Acceleo. 
All these repos are submodules of [Soft](https://github.com/masagroup/soft) project

**Comment by schwichti** [comment]
If you are interested in an experience exchange wrt porting EMF or join forces to develop an ecore runtime library let me know.
